/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitProgram(Program *t) {} //abstract class
void Skeleton::visitTopDef(TopDef *t) {} //abstract class
void Skeleton::visitArg(Arg *t) {} //abstract class
void Skeleton::visitMember(Member *t) {} //abstract class
void Skeleton::visitBlock(Block *t) {} //abstract class
void Skeleton::visitStmt(Stmt *t) {} //abstract class
void Skeleton::visitItem(Item *t) {} //abstract class
void Skeleton::visitDType(DType *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class
void Skeleton::visitBaseType(BaseType *t) {} //abstract class
void Skeleton::visitExpr(Expr *t) {} //abstract class
void Skeleton::visitAddOp(AddOp *t) {} //abstract class
void Skeleton::visitMulOp(MulOp *t) {} //abstract class
void Skeleton::visitRelOp(RelOp *t) {} //abstract class

void Skeleton::visitProg(Prog *prog)
{
  /* Code For Prog Goes Here */

  if (prog->listtopdef_) prog->listtopdef_->accept(this);

}

void Skeleton::visitFnDef(FnDef *fn_def)
{
  /* Code For FnDef Goes Here */

  if (fn_def->dtype_) fn_def->dtype_->accept(this);
  visitIdent(fn_def->ident_);
  if (fn_def->listarg_) fn_def->listarg_->accept(this);
  if (fn_def->block_) fn_def->block_->accept(this);

}

void Skeleton::visitClassDef(ClassDef *class_def)
{
  /* Code For ClassDef Goes Here */

  visitIdent(class_def->ident_);
  if (class_def->listmember_) class_def->listmember_->accept(this);

}

void Skeleton::visitClassExt(ClassExt *class_ext)
{
  /* Code For ClassExt Goes Here */

  visitIdent(class_ext->ident_1);
  visitIdent(class_ext->ident_2);
  if (class_ext->listmember_) class_ext->listmember_->accept(this);

}

void Skeleton::visitAr(Ar *ar)
{
  /* Code For Ar Goes Here */

  if (ar->dtype_) ar->dtype_->accept(this);
  visitIdent(ar->ident_);

}

void Skeleton::visitField(Field *field)
{
  /* Code For Field Goes Here */

  if (field->dtype_) field->dtype_->accept(this);
  visitIdent(field->ident_);

}

void Skeleton::visitMethod(Method *method)
{
  /* Code For Method Goes Here */

  if (method->dtype_) method->dtype_->accept(this);
  visitIdent(method->ident_);
  if (method->listarg_) method->listarg_->accept(this);
  if (method->block_) method->block_->accept(this);

}

void Skeleton::visitBlk(Blk *blk)
{
  /* Code For Blk Goes Here */

  if (blk->liststmt_) blk->liststmt_->accept(this);

}

void Skeleton::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */


}

void Skeleton::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */

  if (b_stmt->block_) b_stmt->block_->accept(this);

}

void Skeleton::visitDecl(Decl *decl)
{
  /* Code For Decl Goes Here */

  if (decl->dtype_) decl->dtype_->accept(this);
  if (decl->listitem_) decl->listitem_->accept(this);

}

void Skeleton::visitAss(Ass *ass)
{
  /* Code For Ass Goes Here */

  if (ass->expr_1) ass->expr_1->accept(this);
  if (ass->expr_2) ass->expr_2->accept(this);

}

void Skeleton::visitIncr(Incr *incr)
{
  /* Code For Incr Goes Here */

  if (incr->expr_) incr->expr_->accept(this);

}

void Skeleton::visitDecr(Decr *decr)
{
  /* Code For Decr Goes Here */

  if (decr->expr_) decr->expr_->accept(this);

}

void Skeleton::visitRet(Ret *ret)
{
  /* Code For Ret Goes Here */

  if (ret->expr_) ret->expr_->accept(this);

}

void Skeleton::visitVRet(VRet *v_ret)
{
  /* Code For VRet Goes Here */


}

void Skeleton::visitCond(Cond *cond)
{
  /* Code For Cond Goes Here */

  if (cond->expr_) cond->expr_->accept(this);
  if (cond->stmt_) cond->stmt_->accept(this);

}

void Skeleton::visitCondElse(CondElse *cond_else)
{
  /* Code For CondElse Goes Here */

  if (cond_else->expr_) cond_else->expr_->accept(this);
  if (cond_else->stmt_1) cond_else->stmt_1->accept(this);
  if (cond_else->stmt_2) cond_else->stmt_2->accept(this);

}

void Skeleton::visitWhile(While *while_)
{
  /* Code For While Goes Here */

  if (while_->expr_) while_->expr_->accept(this);
  if (while_->stmt_) while_->stmt_->accept(this);

}

void Skeleton::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->expr_) s_exp->expr_->accept(this);

}

void Skeleton::visitForEach(ForEach *for_each)
{
  /* Code For ForEach Goes Here */

  if (for_each->type_) for_each->type_->accept(this);
  visitIdent(for_each->ident_);
  if (for_each->expr_) for_each->expr_->accept(this);
  if (for_each->stmt_) for_each->stmt_->accept(this);

}

void Skeleton::visitNoInit(NoInit *no_init)
{
  /* Code For NoInit Goes Here */

  visitIdent(no_init->ident_);

}

void Skeleton::visitInit(Init *init)
{
  /* Code For Init Goes Here */

  visitIdent(init->ident_);
  if (init->expr_) init->expr_->accept(this);

}

void Skeleton::visitDTypeBase(DTypeBase *d_type_base)
{
  /* Code For DTypeBase Goes Here */

  if (d_type_base->basetype_) d_type_base->basetype_->accept(this);

}

void Skeleton::visitDTypeArr(DTypeArr *d_type_arr)
{
  /* Code For DTypeArr Goes Here */

  if (d_type_arr->basetype_) d_type_arr->basetype_->accept(this);

}

void Skeleton::visitTBase(TBase *t_base)
{
  /* Code For TBase Goes Here */

  if (t_base->basetype_) t_base->basetype_->accept(this);

}

void Skeleton::visitTArr(TArr *t_arr)
{
  /* Code For TArr Goes Here */

  if (t_arr->type_) t_arr->type_->accept(this);

}

void Skeleton::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */


}

void Skeleton::visitFun(Fun *fun)
{
  /* Code For Fun Goes Here */

  if (fun->type_) fun->type_->accept(this);
  if (fun->listtype_) fun->listtype_->accept(this);

}

void Skeleton::visitInt(Int *int_)
{
  /* Code For Int Goes Here */


}

void Skeleton::visitStr(Str *str)
{
  /* Code For Str Goes Here */


}

void Skeleton::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */


}

void Skeleton::visitClassT(ClassT *class_t)
{
  /* Code For ClassT Goes Here */

  visitIdent(class_t->ident_);

}

void Skeleton::visitEParen(EParen *e_paren)
{
  /* Code For EParen Goes Here */

  if (e_paren->expr_) e_paren->expr_->accept(this);

}

void Skeleton::visitESelf(ESelf *e_self)
{
  /* Code For ESelf Goes Here */


}

void Skeleton::visitENull(ENull *e_null)
{
  /* Code For ENull Goes Here */


}

void Skeleton::visitECast(ECast *e_cast)
{
  /* Code For ECast Goes Here */

  if (e_cast->type_) e_cast->type_->accept(this);
  if (e_cast->expr_) e_cast->expr_->accept(this);

}

void Skeleton::visitENewArr(ENewArr *e_new_arr)
{
  /* Code For ENewArr Goes Here */

  if (e_new_arr->basetype_) e_new_arr->basetype_->accept(this);
  if (e_new_arr->expr_) e_new_arr->expr_->accept(this);

}

void Skeleton::visitENewObj(ENewObj *e_new_obj)
{
  /* Code For ENewObj Goes Here */

  visitIdent(e_new_obj->ident_);

}

void Skeleton::visitEVar(EVar *e_var)
{
  /* Code For EVar Goes Here */

  visitIdent(e_var->ident_);

}

void Skeleton::visitELitInt(ELitInt *e_lit_int)
{
  /* Code For ELitInt Goes Here */

  visitInteger(e_lit_int->integer_);

}

void Skeleton::visitELitTrue(ELitTrue *e_lit_true)
{
  /* Code For ELitTrue Goes Here */


}

void Skeleton::visitELitFalse(ELitFalse *e_lit_false)
{
  /* Code For ELitFalse Goes Here */


}

void Skeleton::visitEString(EString *e_string)
{
  /* Code For EString Goes Here */

  visitString(e_string->string_);

}

void Skeleton::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitIdent(e_app->ident_);
  if (e_app->listexpr_) e_app->listexpr_->accept(this);

}

void Skeleton::visitEIndex(EIndex *e_index)
{
  /* Code For EIndex Goes Here */

  if (e_index->expr_1) e_index->expr_1->accept(this);
  if (e_index->expr_2) e_index->expr_2->accept(this);

}

void Skeleton::visitEMethod(EMethod *e_method)
{
  /* Code For EMethod Goes Here */

  if (e_method->expr_) e_method->expr_->accept(this);
  visitIdent(e_method->ident_);
  if (e_method->listexpr_) e_method->listexpr_->accept(this);

}

void Skeleton::visitEField(EField *e_field)
{
  /* Code For EField Goes Here */

  if (e_field->expr_) e_field->expr_->accept(this);
  visitIdent(e_field->ident_);

}

void Skeleton::visitNeg(Neg *neg)
{
  /* Code For Neg Goes Here */

  if (neg->expr_) neg->expr_->accept(this);

}

void Skeleton::visitNot(Not *not_)
{
  /* Code For Not Goes Here */

  if (not_->expr_) not_->expr_->accept(this);

}

void Skeleton::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->expr_1) e_mul->expr_1->accept(this);
  if (e_mul->mulop_) e_mul->mulop_->accept(this);
  if (e_mul->expr_2) e_mul->expr_2->accept(this);

}

void Skeleton::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->expr_1) e_add->expr_1->accept(this);
  if (e_add->addop_) e_add->addop_->accept(this);
  if (e_add->expr_2) e_add->expr_2->accept(this);

}

void Skeleton::visitERel(ERel *e_rel)
{
  /* Code For ERel Goes Here */

  if (e_rel->expr_1) e_rel->expr_1->accept(this);
  if (e_rel->relop_) e_rel->relop_->accept(this);
  if (e_rel->expr_2) e_rel->expr_2->accept(this);

}

void Skeleton::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->expr_1) e_and->expr_1->accept(this);
  if (e_and->expr_2) e_and->expr_2->accept(this);

}

void Skeleton::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->expr_1) e_or->expr_1->accept(this);
  if (e_or->expr_2) e_or->expr_2->accept(this);

}

void Skeleton::visitPlus(Plus *plus)
{
  /* Code For Plus Goes Here */


}

void Skeleton::visitMinus(Minus *minus)
{
  /* Code For Minus Goes Here */


}

void Skeleton::visitTimes(Times *times)
{
  /* Code For Times Goes Here */


}

void Skeleton::visitDiv(Div *div)
{
  /* Code For Div Goes Here */


}

void Skeleton::visitMod(Mod *mod)
{
  /* Code For Mod Goes Here */


}

void Skeleton::visitLTH(LTH *lth)
{
  /* Code For LTH Goes Here */


}

void Skeleton::visitLE(LE *le)
{
  /* Code For LE Goes Here */


}

void Skeleton::visitGTH(GTH *gth)
{
  /* Code For GTH Goes Here */


}

void Skeleton::visitGE(GE *ge)
{
  /* Code For GE Goes Here */


}

void Skeleton::visitEQU(EQU *equ)
{
  /* Code For EQU Goes Here */


}

void Skeleton::visitNE(NE *ne)
{
  /* Code For NE Goes Here */


}


void Skeleton::visitListTopDef(ListTopDef *list_top_def)
{
  for (ListTopDef::iterator i = list_top_def->begin() ; i != list_top_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListMember(ListMember *list_member)
{
  for (ListMember::iterator i = list_member->begin() ; i != list_member->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListStmt(ListStmt *list_stmt)
{
  for (ListStmt::iterator i = list_stmt->begin() ; i != list_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListItem(ListItem *list_item)
{
  for (ListItem::iterator i = list_item->begin() ; i != list_item->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



